server:
  port: ${PORT:8080}
  address: 0.0.0.0



spring:
  application:
    name: agri-gateway-service
  cloud:
    gateway:
      routes:
        - id: agri-user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/agri-user-service/**
  graphql:
    graphiql:
      enabled: true
    schema:
      locations: classpath:graphql/
      file-extensions: .graphqls

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
  packages-to-scan: com.agritrust.gateway.controller

logging:
  level:
    com.agritrust: DEBUG
    org.springframework.graphql: DEBUG 
