name: Deploy Gateway to Cloud Run

on:
  push:
    paths:
      - 'AgriGatewayService/**'  # Only trigger when files in this folder change
    branches: [ main ]

jobs:
  deploy:
    name: Build and Deploy Gateway to Cloud Run
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: AgriGatewayService  # 👈 Set the working directory

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set Project ID
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker gcr.io

      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/agri-gateway-service .

      - name: Push Docker image
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/agri-gateway-service

      - name: Set Cloud Run IAM Policy
        run: |
          gcloud run services add-iam-policy-binding gateway-service \
          --region=asia-south1 \
          --member="allUsers" \
          --role="roles/run.invoker"
   
        
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: gateway-service
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/agri-gateway-service
          region: asia-south1
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          timeout: 600s
          flags: '--allow-unauthenticated'
