name: Deploy Gateway Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build with Maven
        working-directory: AgriGatewayService
        run: mvn clean package -DskipTests
        
      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/agri-gateway-service:latest \
            -f AgriGatewayService/Dockerfile \
            AgriGatewayService
              
      - name:  push Docker image
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/agri-gateway-service:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: gateway-service
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/agri-gateway-service
          region: asia-south1
          allow-unauthenticated: true
